### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by marcioAlmada** [marcioAlmada/yay#3]
- [x] Pick a more ergonomic composition identifier (instead of middle dot ·), before the DSL leaves draft state. Done: `$(`  and `)`
- [x] Literal matchers and expansions
- [x] Token type matchers and expansions like `T_TYPE·label`. Ex: `T_STRING·name`
- [x] Greedy layer matching and expansion `{···label}`, `[···label]`, `(···label)`
- [x] Non dominant macros (macros that only expand if fully matched and never throw errors during matching)
- [x] Macro escaping (cloaking) syntax #9
- [x] Dominant macros (macros that throw syntax errors if not fulfilled after a given entry point) #6 
- [x] (Partial) Expansion iteration like `·matched_scope ··· { ·a ·b ·c }`
- [x] Make expansion context unpacking become recursive #10
  - [ ] **Maybe** allow index access on expansions: `·matched[0] ·matched[2] ·matched[1]`
- [x] Allow control of trailing elements during ast unpacking #21
- [x] Disallow infinite recursion by default while expanding macros #2
- [x] Allow macro to refer to itself with `·this`
- [x] Macro hygiene #8
- [x] Macro tags #4
  - [x] `·recursion` tag to force a macro to be recursive #5 
  - [ ] maybe allow tag parameters, like `·recursion(limit => 3)`
- [x] Add more high level parsers
  - [x] `·expression()` or `·exp()`
  - [x] `·midrule(function($ts){...})`
  - [x] `·ls(...)`
  - [x] `·word()`
  - [x] `·label()`
  - [x] `·string()`
  - [x] `·variable()`
- [x] Add more high level expanders [@](https://github.com/marcioAlmada/yay/blob/master/src/expanders.php)
  - [x] `·stringify(...)`
  - [x] `·concat(...)`
  - [x] `·eval()`
- [ ] Allow operator precedence and infix macros declarations
- [x] Allow macro importing between files like `use macro some\file{macro_name}` (right now macros are limited to be local per file)
- [x] Global macros #28
- [x] Support user defined parsers and expanders (add proper D.I for DSL lookups)
- [x] **Real time mode**: pass included files through the preprocessor automatically #11
  - [x] Provide a stream wrapper for pre processing  inclusion `include 'yay://some_file.php';`
  - [ ] Composer integration
  - [x] Make it fast enough
    - [x] Disable complex errors by default #7
    - [ ] Optional: create a goto based parser stack interpreter and try to save tons of function calls
- [ ] Write more documentation

**Comment by chris-kruining** [comment]
I thought I'd poke you for an update of the roadmap :wink: 

- [x]  Pick a more ergonomic composition identifier (instead of middle dot ·), before the DSL leaves draft state.
- [x] Literal matchers and expansions
- [x] Token type matchers and expansions like T_TYPE·label. Ex: T_STRING·name
- [x] Greedy layer matching and expansion {···label}, [···label], (···label)
- [x] Non dominant macros (macros that only expand if fully matched and never throw errors during matching)
- [x] Macro escaping (cloaking) syntax #9
- [x] Dominant macros (macros that throw syntax errors if not fulfilled after a given entry point) #6
 (Partial) Expansion iteration like ·matched_scope ··· { ·a ·b ·c }
- [x] Make expansion context unpacking become recursive #10
    - [x] Maybe allow index access on expansions: ·matched[0] ·matched[2] ·matched[1]
- [x] Allow control of trailing elements during ast unpacking #21
- [x] Disallow infinite recursion by default while expanding macros #2
- [x] Allow macro to refer to itself with ·this
- [x] Macro hygiene #8
- [x] Macro tags #4
    - [x] ·recursion tag to force a macro to be recursive #5
    - [ ] maybe allow tag parameters, like ·recursion(limit => 3)
- [x] Add more high level parsers
    - [x] ·expression() or ·exp()
    - [x] ·midrule(function($ts){...})
    - [x] ·ls(...)
    - [x] ·word()
    - [x] ·label()
    - [x] ·string()
    - [x] ·variable()
- [ ] Add more high level expanders @
    - [x] ·stringify(...)
    - [x] ·concat(...)
    - [ ] ·eval()
- [ ] Allow operator precedence and infix macros declarations
- [ ] Allow macro importing between files like use macro some\file{macro_name} (right now macros are limited to be local per file)
- [x] Global macros #28
- [ ] Support user defined parsers and expanders (add proper D.I for DSL lookups)
- [ ] Real time mode: pass included files through the preprocessor automatically #11
- [x] Provide a stream wrapper for pre processing inclusion include 'yay://some_file.php';
    - [ ] Composer integration
    - [x] Make it fast enough
        - [x] Disable complex errors by default #7
        - [ ] Optional: create a goto based parser stack interpreter and try to save tons of function calls
- [ ] Write more documentation

**Comment by chris-kruining** [comment]
have you by any chanche written down somewhere waht you want with the composer integration part? maybe I could help out with that :smile:

**Comment by marcioAlmada** [comment]
@chris-kruining there are two alternatives for composer integration. One is using [*preprocess*](https://preprocess.io/) and the other is using [Xray](https://github.com/marcioAlmada/xray) and loading the preprocessor callback before anything else.
